# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5235159f73c0a7b857e9cba59d7107daad0c22720beef94aa3dab7d9438f848a4255a1fc437f56ee16954ad8ed2eeb654de014c462d2f8926cef0bd114b46a8c

test:
  secret_key_base: 3ca6cda9b2ef0aa448a1cb713383fe869702ebb34882ac094af885b008fdb0f984a9cf544b9c7549fee316ebc6b93c526310507f356c398a26a5e90274ea916f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
